

services:
  backend:
    image: my-backend-image
    container_name: backend
    ports:
      - "8081:8081" # 백엔드 포트 매핑
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/shppingmal_db
      - SPRING_DATASOURCE_USERNAME=jje
      - SPRING_DATASOURCE_PASSWORD=wjdwndms12!
    networks:
      - app-network

    frontend:
      image: my-frontend-image
      container_name: frontend
      ports:
        - "3000:3000" # 프론트엔드 포트 매핑
      environment:
        - REACT_APP_API_URL=http://backend:8081 # 백엔드 서비스에 대한 내부 링크
      networks:
        - app-network
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: wjdwndms12!
      MYSQL_DATABASE: shppingmal_db
      MYSQL_USER: jje
      MYSQL_PASSWORD: wjdwndms12!
    ports:
      - "3307:3306" #3306 포트가 이미 다른 프로세스에서 사용 중이어서 충돌방지를 위해 3307로 설정
    networks:
      - app-network

networks:
  app-network:
    driver: bridge